### ISSUE TITLE
STATICFILES_DIRS warnings

### ISSUE THREAD

**Issue by Dwiga** [Louxsdon/django-breeze#5]
WARNINGS:
?: (staticfiles.W004) The directory '/Users/dwiga/Playground/dwilab/silvertech/src/public' in the STATICFILES_DIRS setting does not exist.
?: (staticfiles.W004) The directory 'static/dist' in the STATICFILES_DIRS setting does not exist.

**To Reproduce**
appeared soon after running the app `python manage.py runserver`

**Expected behavior**
No issues appeared

**Desktop (please complete the following information):**
 - OS: Mac OS X
 
 How to fix the issue? something I need to do?

**Comment by rvyhvn** [comment]
simply add `dist/` folder inside `static/` folder and the warning will gone.

**Comment by Dwiga** [comment]
> simply add `dist/` folder inside `static/` folder and the warning will gone.

thanks
